all:
  hosts:
    gpu-ml-01:
      ansible_host: 212.74.224.231
      ansible_user: root
      ansible_port: 22022
      ansible_ssh_private_key_file: ~/.ssh/selectel_ds_scan
  children:
    ml_nodes:
      hosts:
        gpu-ml-01:
