github_runner_version: "2.322.0"
github_runner_user: mlops
github_runner_base_dir: /opt/github-runners

# List of runners to install on this host
# Each item requires: name, repo_url, token, labels
github_runners: []
